version: 2
updates:
  # Enable version updates for Cargo
  - package-ecosystem: "cargo"
    directory: "/rs/mdbook-footnote"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/rs/wasm"
    schedule:
      interval: "weekly"

    groups:
      all:
        patterns:
          - "*"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/scss"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/js"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
