[package]
name = "wasm"
version = "0.0.1"
authors = ["CoralPink <teqt6ytqt@mozmail.com>"]
edition = "2021"
rust-version = "1.71"
homepage = "https://github.com/CoralPink"
repository = "https://github.com/CoralPink/commentary"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "Element",
  "Window",
]
