[package]
name = "wasm-book"
version = "0.2.0"
authors = ["CoralPink <teqt6ytqt@mozmail.com>"]
edition = "2021"
rust-version = "1.70"
description = "This is the WebAssembly code used on this site."
homepage = "https://github.com/CoralPink"
repository = "https://github.com/CoralPink/commentary"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
js-sys = "0.3"
rust-stemmers = "1.2"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "Element",
  "NodeList",
  "Window",
]
