[package]
name = "wasm-book"
version = "0.6.0"
authors = ["CoralPink <teqt6ytqt@mozmail.com>"]
edition = "2021"
rust-version = "1.74"
description = "This is the WebAssembly code used on this site."
homepage = "https://github.com/CoralPink"
repository = "https://github.com/CoralPink/commentary"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[workspace]
members = ["macros"]

[profile.release]
lto = "fat"
opt-level = "s"
strip = "symbols"

[dependencies]
js-sys = "=0.3.72"
macros = { path = "macros" }
serde = { version = "=1.0.211", features = ["derive"] }
serde-wasm-bindgen = "=0.6.5"
wasm-bindgen = "=0.2.95"

[dependencies.web-sys]
version = "=0.3.72"
features = [
  "Document",
  "Element",
  "HtmlElement",
  "NodeList",
  "Window",
]

[dev-dependencies]
wasm-bindgen-test = "=0.3.45"
