[package]
name = "wasm-book"
version = "0.9.0"
authors = ["CoralPink <teqt6ytqt@mozmail.com>"]
edition = "2024"
rust-version = "1.85"
description = "This is the WebAssembly code used on this site."
homepage = "https://github.com/CoralPink"
repository = "https://github.com/CoralPink/commentary"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[workspace]
members = ["macros"]

[profile.release]
lto = "fat"
opt-level = "s"
strip = "symbols"

[dependencies]
arrayvec = "=0.7.6"
html-escape = "=0.2.13"
js-sys = "=0.3.77"
macros = { path = "macros" }
serde = { version = "=1.0.219", features = ["derive"] }
serde-wasm-bindgen = "=0.6.5"
urlencoding = "=2.1.3"
wasm-bindgen = "=0.2.100"

[dependencies.web-sys]
version = "=0.3.77"
features = [
  "Document",
  "Element",
  "NodeList",
  "Window",
]

[dev-dependencies]
wasm-bindgen-test = "=0.3.50"
