#!/usr/bin/env zsh
# shellcheck shell=zsh
set -euo pipefail

input=${1:-toc.html}
output=${2:-pagelist.html}

if [ ! -f toc.html ]; then
  echo "Error: '$input' not found" >&2
  exit 1
fi

# This script processes the toc.html file generated by mdbook
# to create a simplified pagelist.html by:
# 1. Replacing section class with regular ol
# 2. Simplifying chapter item li elements
# 3. Removing target="_parent" attributes
sed \
  -e 's|<ol class="section">|<ol>|g' \
  -e 's|<li class="chapter-item expanded ">|<li>|g' \
  -e 's| target="_parent"||g' \
  "$input" > "$output"
