name: Test mdBook Backend

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-mdbook-backend:
    name: Test mdBook Backend
    runs-on: macos-14
    steps:
      - name: Checkout the repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          sparse-checkout: |
            rs/mdbook-footnote

      - name: Cache Cargo
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: build-test-backend${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Test Cargo (mdbook-footnote)
        working-directory: rs/mdbook-footnote
        run: |
          cargo test --verbose

