name: test rs footnote

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Moving directories
      run: cd rs/mdbook-footnote

    - name: Run tests
      run: cargo test --verbose
