name: test-cargo-rs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_job:
    runs-on: macos-14
    steps:
      - name: Checkout the repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          sparse-checkout: |
            rs

      - name: Test Cargo
        working-directory: rs
        run: |
          cargo test --verbose
